M48
; DRILL file {KiCad 9.0.2} date 2025-07-20T12:12:04-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-20T12:12:04-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X50.8Y-83.167
T2
X58.42Y-38.505
X58.42Y-41.505
M30
